//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireEscape.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireEscape.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные размеры площадки.
        /// </summary>
        internal static string AdditionalPlatformSizes {
            get {
                return ResourceManager.GetString("AdditionalPlatformSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить заказ.
        /// </summary>
        internal static string AddOrderError {
            get {
                return ResourceManager.GetString("AddOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить фотографию в  протокол.
        /// </summary>
        internal static string AddPhotoError {
            get {
                return ResourceManager.GetString("AddPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить протокол.
        /// </summary>
        internal static string AddProtocolError {
            get {
                return ResourceManager.GetString("AddProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес объекта.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите адрес объекта.
        /// </summary>
        internal static string AddressHint {
            get {
                return ResourceManager.GetString("AddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string AddressStringFormat {
            get {
                return ResourceManager.GetString("AddressStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить элемент лестницы.
        /// </summary>
        internal static string AddStairsElementError {
            get {
                return ResourceManager.GetString("AddStairsElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Escape.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поврежденные данные.
        /// </summary>
        internal static string BrokenData {
            get {
                return ResourceManager.GetString("BrokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на здание.
        /// </summary>
        internal static string BuildingMountedTrim {
            get {
                return ResourceManager.GetString("BuildingMountedTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string CaptionDivider {
            get {
                return ResourceManager.GetString("CaptionDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте подключение к интернет и повторите операцию..
        /// </summary>
        internal static string CheckInternetMessage {
            get {
                return ResourceManager.GetString("CheckInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копия.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скопировать протокол.
        /// </summary>
        internal static string CopyProtocolError {
            get {
                return ResourceManager.GetString("CopyProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скопировать элемент лестницы.
        /// </summary>
        internal static string CopyStairsElementError {
            get {
                return ResourceManager.GetString("CopyStairsElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скопировать лестницу.
        /// </summary>
        internal static string CopyStairsError {
            get {
                return ResourceManager.GetString("CopyStairsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать файл отчета.
        /// </summary>
        internal static string CreateReportError {
            get {
                return ResourceManager.GetString("CreateReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представитель заказчика.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите представителя заказчика.
        /// </summary>
        internal static string CustomerHint {
            get {
                return ResourceManager.GetString("CustomerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деформация.
        /// </summary>
        internal static string Deformation {
            get {
                return ResourceManager.GetString("Deformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите размер деформации.
        /// </summary>
        internal static string DeformationHint {
            get {
                return ResourceManager.GetString("DeformationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить заказ?.
        /// </summary>
        internal static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить заказ.
        /// </summary>
        internal static string DeleteOrderError {
            get {
                return ResourceManager.GetString("DeleteOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить протокол?.
        /// </summary>
        internal static string DeleteProtocol {
            get {
                return ResourceManager.GetString("DeleteProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить протокол.
        /// </summary>
        internal static string DeleteProtocolError {
            get {
                return ResourceManager.GetString("DeleteProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить элемент лестницы?.
        /// </summary>
        internal static string DeleteStairsElement {
            get {
                return ResourceManager.GetString("DeleteStairsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить элемент лестницы.
        /// </summary>
        internal static string DeleteStairsElementError {
            get {
                return ResourceManager.GetString("DeleteStairsElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить учетную запись?.
        /// </summary>
        internal static string DeleteUserAccount {
            get {
                return ResourceManager.GetString("DeleteUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить учетную запись пользователя.
        /// </summary>
        internal static string DeleteUserAccountError {
            get {
                return ResourceManager.GetString("DeleteUserAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отредактировать заказ.
        /// </summary>
        internal static string EditOrderError {
            get {
                return ResourceManager.GetString("EditOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отредактировать протокол.
        /// </summary>
        internal static string EditProtocolError {
            get {
                return ResourceManager.GetString("EditProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отркдактировать параметры лестницы.
        /// </summary>
        internal static string EditStairsError {
            get {
                return ResourceManager.GetString("EditStairsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отредактировать учетную запись пользователя.
        /// </summary>
        internal static string EditUserAccountError {
            get {
                return ResourceManager.GetString("EditUserAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер элемента.
        /// </summary>
        internal static string ElementNumber {
            get {
                return ResourceManager.GetString("ElementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер элемента.
        /// </summary>
        internal static string ElementNumberHint {
            get {
                return ResourceManager.GetString("ElementNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на перепаде.
        /// </summary>
        internal static string ElevationMountedTrim {
            get {
                return ResourceManager.GetString("ElevationMountedTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эвакуационная лестница.
        /// </summary>
        internal static string EscapeStairs {
            get {
                return ResourceManager.GetString("EscapeStairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to эвакуац.
        /// </summary>
        internal static string EscapeStairsTrim {
            get {
                return ResourceManager.GetString("EscapeStairsTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель заказа.
        /// </summary>
        internal static string ExecutiveCompany {
            get {
                return ResourceManager.GetString("ExecutiveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите  исполнителя заказа.
        /// </summary>
        internal static string ExecutiveCompanyHint {
            get {
                return ResourceManager.GetString("ExecutiveCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите подпись исполнителя.
        /// </summary>
        internal static string ExecutorSignHint {
            get {
                return ResourceManager.GetString("ExecutorSignHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счетчик окончания учетной записи.
        /// </summary>
        internal static string ExpirationCount {
            get {
                return ResourceManager.GetString("ExpirationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания учетной записи.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует ограждение для П1-2.
        /// </summary>
        internal static string FenceAbsentHint {
            get {
                return ResourceManager.GetString("FenceAbsentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установите доступ к управлению всеми файлами!.
        /// </summary>
        internal static string FilesAccessPermissionWarning {
            get {
                return ResourceManager.GetString("FilesAccessPermissionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожарная лестница.
        /// </summary>
        internal static string FireEscape {
            get {
                return ResourceManager.GetString("FireEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер испытуемого объекта.
        /// </summary>
        internal static string FireEscapeNum {
            get {
                return ResourceManager.GetString("FireEscapeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название объекта.
        /// </summary>
        internal static string FireEscapeObject {
            get {
                return ResourceManager.GetString("FireEscapeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название объекта.
        /// </summary>
        internal static string FireEscapeObjectHint {
            get {
                return ResourceManager.GetString("FireEscapeObjectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить список заказов.
        /// </summary>
        internal static string GetOrdersError {
            get {
                return ResourceManager.GetString("GetOrdersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить список протоколов.
        /// </summary>
        internal static string GetProtocolsError {
            get {
                return ResourceManager.GetString("GetProtocolsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить удаленный лог.
        /// </summary>
        internal static string GetRemoteLogError {
            get {
                return ResourceManager.GetString("GetRemoteLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить список пользователей.
        /// </summary>
        internal static string GetUserAccountsError {
            get {
                return ResourceManager.GetString("GetUserAccountsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ.
        /// </summary>
        internal static string Gost {
            get {
                return ResourceManager.GetString("Gost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расст. от земли.
        /// </summary>
        internal static string GroundDistance {
            get {
                return ResourceManager.GetString("GroundDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите расстояние от земли.
        /// </summary>
        internal static string GroundDistanceHint {
            get {
                return ResourceManager.GetString("GroundDistanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длинна.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите город / область.
        /// </summary>
        internal static string LocationHint {
            get {
                return ResourceManager.GetString("LocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        internal static string MakePhotoHint {
            get {
                return ResourceManager.GetString("MakePhotoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый протокол.
        /// </summary>
        internal static string NewProtocol {
            get {
                return ResourceManager.GetString("NewProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет подключения.
        /// </summary>
        internal static string NoConnectivity {
            get {
                return ResourceManager.GetString("NoConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество протоколов.
        /// </summary>
        internal static string NumberOfProtocols {
            get {
                return ResourceManager.GetString("NumberOfProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отредкатировать учетные записи пользователей.
        /// </summary>
        internal static string OpenUserAccountMainPageError {
            get {
                return ResourceManager.GetString("OpenUserAccountMainPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заказа.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе нет протоколов.
        /// </summary>
        internal static string OrderIsEmpty {
            get {
                return ResourceManager.GetString("OrderIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список заказов.
        /// </summary>
        internal static string OrderMainPageTitle {
            get {
                return ResourceManager.GetString("OrderMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ.
        /// </summary>
        internal static string OrderName {
            get {
                return ResourceManager.GetString("OrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название заказа.
        /// </summary>
        internal static string OrderNameHint {
            get {
                return ResourceManager.GetString("OrderNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы протоколов заказа.
        /// </summary>
        internal static string OrderReport {
            get {
                return ResourceManager.GetString("OrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск заказов....
        /// </summary>
        internal static string OrdersSearch {
            get {
                return ResourceManager.GetString("OrdersSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верт.
        /// </summary>
        internal static string P1Trim {
            get {
                return ResourceManager.GetString("P1Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марш.
        /// </summary>
        internal static string P2Trim {
            get {
                return ResourceManager.GetString("P2Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр PDF файла.
        /// </summary>
        internal static string PdfView {
            get {
                return ResourceManager.GetString("PdfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует площадка П2.
        /// </summary>
        internal static string PlatformAbsentHint {
            get {
                return ResourceManager.GetString("PlatformAbsentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина площадки.
        /// </summary>
        internal static string PlatformLength {
            get {
                return ResourceManager.GetString("PlatformLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите длину площадки.
        /// </summary>
        internal static string PlatformLengthHint {
            get {
                return ResourceManager.GetString("PlatformLengthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sплощ.
        /// </summary>
        internal static string PlatformSize {
            get {
                return ResourceManager.GetString("PlatformSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м2.
        /// </summary>
        internal static string PlatformSizeUnit {
            get {
                return ResourceManager.GetString("PlatformSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите количество балок площадки.
        /// </summary>
        internal static string PlatformSupportBeamsCountHint {
            get {
                return ResourceManager.GetString("PlatformSupportBeamsCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина площадки.
        /// </summary>
        internal static string PlatformWidth {
            get {
                return ResourceManager.GetString("PlatformWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите ширину площадки.
        /// </summary>
        internal static string PlatformWidthHint {
            get {
                return ResourceManager.GetString("PlatformWidthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель №1.
        /// </summary>
        internal static string PrimaryExecutorSign {
            get {
                return ResourceManager.GetString("PrimaryExecutorSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество защитных покрытий соответствует ГОСТ.
        /// </summary>
        internal static string ProtectiveServiceability {
            get {
                return ResourceManager.GetString("ProtectiveServiceability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протокол.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата протокола.
        /// </summary>
        internal static string ProtocolDate {
            get {
                return ResourceManager.GetString("ProtocolDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список протоколов.
        /// </summary>
        internal static string ProtocolMainPageTitle {
            get {
                return ResourceManager.GetString("ProtocolMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер протокола.
        /// </summary>
        internal static string ProtocolNum {
            get {
                return ResourceManager.GetString("ProtocolNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск протоколов....
        /// </summary>
        internal static string ProtocolsSearch {
            get {
                return ResourceManager.GetString("ProtocolsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несоотв. ГОСТ.
        /// </summary>
        internal static string RejectExplanation {
            get {
                return ResourceManager.GetString("RejectExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите выявленные несоответствия.
        /// </summary>
        internal static string RejectExplanationHint {
            get {
                return ResourceManager.GetString("RejectExplanationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несоотв.
        /// </summary>
        internal static string RejectExplanationLabel {
            get {
                return ResourceManager.GetString("RejectExplanationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаленный лог.
        /// </summary>
        internal static string RemoteLog {
            get {
                return ResourceManager.GetString("RemoteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадка выхода на кровлю.
        /// </summary>
        internal static string RoofPlatform {
            get {
                return ResourceManager.GetString("RoofPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сохранить заказ.
        /// </summary>
        internal static string SaveOrderError {
            get {
                return ResourceManager.GetString("SaveOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сохранить протокол.
        /// </summary>
        internal static string SaveProtocolError {
            get {
                return ResourceManager.GetString("SaveProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сохранить учетную запись.
        /// </summary>
        internal static string SaveUserAccountError {
            get {
                return ResourceManager.GetString("SaveUserAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель №2.
        /// </summary>
        internal static string SecondaryExecutorSign {
            get {
                return ResourceManager.GetString("SecondaryExecutorSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        internal static string SelectPhotoHint {
            get {
                return ResourceManager.GetString("SelectPhotoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете элемент.
        /// </summary>
        internal static string SelectStairsElement {
            get {
                return ResourceManager.GetString("SelectStairsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соотв. ГОСТ.
        /// </summary>
        internal static string Serviceability {
            get {
                return ResourceManager.GetString("Serviceability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка архива заказа.
        /// </summary>
        internal static string SharingOrderZip {
            get {
                return ResourceManager.GetString("SharingOrderZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лестница.
        /// </summary>
        internal static string Stairs {
            get {
                return ResourceManager.GetString("Stairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементы лестницы.
        /// </summary>
        internal static string StairsElements {
            get {
                return ResourceManager.GetString("StairsElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограждение лестниц.
        /// </summary>
        internal static string StairsFence {
            get {
                return ResourceManager.GetString("StairsFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота ограждения.
        /// </summary>
        internal static string StairsFenceHeight {
            get {
                return ResourceManager.GetString("StairsFenceHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите высоту ограждения.
        /// </summary>
        internal static string StairsFenceHeightHint {
            get {
                return ResourceManager.GetString("StairsFenceHeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота лестницы.
        /// </summary>
        internal static string StairsHeight {
            get {
                return ResourceManager.GetString("StairsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите высоту лестницы.
        /// </summary>
        internal static string StairsHeightHint {
            get {
                return ResourceManager.GetString("StairsHeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите тип установки лестницы.
        /// </summary>
        internal static string StairsMountTypesHint {
            get {
                return ResourceManager.GetString("StairsMountTypesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры лестницы.
        /// </summary>
        internal static string StairsPageTitle {
            get {
                return ResourceManager.GetString("StairsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадка.
        /// </summary>
        internal static string StairsPlatform {
            get {
                return ResourceManager.GetString("StairsPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ступени лестниц.
        /// </summary>
        internal static string StairsSteps {
            get {
                return ResourceManager.GetString("StairsSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лест.
        /// </summary>
        internal static string StairsTrim {
            get {
                return ResourceManager.GetString("StairsTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите тип лестницы.
        /// </summary>
        internal static string StairsTypesHint {
            get {
                return ResourceManager.GetString("StairsTypesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина лестницы.
        /// </summary>
        internal static string StairsWidth {
            get {
                return ResourceManager.GetString("StairsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите ширину лестницы.
        /// </summary>
        internal static string StairsWidthHint {
            get {
                return ResourceManager.GetString("StairsWidthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марш.
        /// </summary>
        internal static string Stairway {
            get {
                return ResourceManager.GetString("Stairway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует марш П2.
        /// </summary>
        internal static string StairwayAbsentHint {
            get {
                return ResourceManager.GetString("StairwayAbsentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина марша.
        /// </summary>
        internal static string StairwayLength {
            get {
                return ResourceManager.GetString("StairwayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите длину марша.
        /// </summary>
        internal static string StairwayLengthHint {
            get {
                return ResourceManager.GetString("StairwayLengthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите количество ступеней марша.
        /// </summary>
        internal static string StairwayStepsCountHint {
            get {
                return ResourceManager.GetString("StairwayStepsCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите количество балок марша.
        /// </summary>
        internal static string StairwaySupportBeamsCountHint {
            get {
                return ResourceManager.GetString("StairwaySupportBeamsCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во ступеней.
        /// </summary>
        internal static string StepsCount {
            get {
                return ResourceManager.GetString("StepsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите кол-во ступеней лестницы.
        /// </summary>
        internal static string StepsCountHint {
            get {
                return ResourceManager.GetString("StepsCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расст. между ступенями.
        /// </summary>
        internal static string StepsDistance {
            get {
                return ResourceManager.GetString("StepsDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите расст. между ступенями.
        /// </summary>
        internal static string StepsDistanceHint {
            get {
                return ResourceManager.GetString("StepsDistanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота ступени.
        /// </summary>
        internal static string StepsHeight {
            get {
                return ResourceManager.GetString("StepsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите высоту ступени.
        /// </summary>
        internal static string StepsHeightHint {
            get {
                return ResourceManager.GetString("StepsHeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина ступени.
        /// </summary>
        internal static string StepsWidth {
            get {
                return ResourceManager.GetString("StepsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите ширину ступени.
        /// </summary>
        internal static string StepsWidthHint {
            get {
                return ResourceManager.GetString("StepsWidthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балки крепления лестниц.
        /// </summary>
        internal static string SupportBeams {
            get {
                return ResourceManager.GetString("SupportBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество балок.
        /// </summary>
        internal static string SupportBeamsCount {
            get {
                return ResourceManager.GetString("SupportBeamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите количество балок.
        /// </summary>
        internal static string SupportBeamsCountHint {
            get {
                return ResourceManager.GetString("SupportBeamsCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество балок (парами).
        /// </summary>
        internal static string SupportBeamsPairsCount {
            get {
                return ResourceManager.GetString("SupportBeamsPairsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите количество балок (парами).
        /// </summary>
        internal static string SupportBeamsPairsCountHint {
            get {
                return ResourceManager.GetString("SupportBeamsPairsCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество точек испытаний.
        /// </summary>
        internal static string TestPointCount {
            get {
                return ResourceManager.GetString("TestPointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите количество точек испытаний.
        /// </summary>
        internal static string TestPointCountHint {
            get {
                return ResourceManager.GetString("TestPointCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точек испытаний.
        /// </summary>
        internal static string TestPointCountTrim {
            get {
                return ResourceManager.GetString("TestPointCountTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Незарегистрированная версия приложения либо действие учетной записи истекло. Сообщите номер {0} вендору приложения..
        /// </summary>
        internal static string UnregisteredApplicationMessage {
            get {
                return ResourceManager.GetString("UnregisteredApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись пользователя.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите компанию учетной записи.
        /// </summary>
        internal static string UserAccountCompanyHint {
            get {
                return ResourceManager.GetString("UserAccountCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор учетной записи.
        /// </summary>
        internal static string UserAccountId {
            get {
                return ResourceManager.GetString("UserAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите идентификатор учетной записи.
        /// </summary>
        internal static string UserAccountIdHint {
            get {
                return ResourceManager.GetString("UserAccountIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string UserAccountMainPageTitle {
            get {
                return ResourceManager.GetString("UserAccountMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string UserAccountName {
            get {
                return ResourceManager.GetString("UserAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите имя пользователя.
        /// </summary>
        internal static string UserAccountNameHint {
            get {
                return ResourceManager.GetString("UserAccountNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите подпись пользователя.
        /// </summary>
        internal static string UserAccountSignatureHint {
            get {
                return ResourceManager.GetString("UserAccountSignatureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск учетных записей....
        /// </summary>
        internal static string UserAccountsSearch {
            get {
                return ResourceManager.GetString("UserAccountsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка валидации:.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расст. до стены.
        /// </summary>
        internal static string WallDistance {
            get {
                return ResourceManager.GetString("WallDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите расстояние до стены.
        /// </summary>
        internal static string WallDistanceHint {
            get {
                return ResourceManager.GetString("WallDistanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество сварных швов соответствует ГОСТ.
        /// </summary>
        internal static string WeldSeamServiceability {
            get {
                return ResourceManager.GetString("WeldSeamServiceability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нагрузка.
        /// </summary>
        internal static string WithstandLoad {
            get {
                return ResourceManager.GetString("WithstandLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кгс.
        /// </summary>
        internal static string WithstandLoadUnit {
            get {
                return ResourceManager.GetString("WithstandLoadUnit", resourceCulture);
            }
        }
    }
}
